#Eureka client properties to register service as a client on eureka server

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: apigateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: USERSERVICE
            uri: lb://USERSERVICE
            predicates:
              - Path=/users/**
            filters:
              - StripPrefix=1


          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
              - Path=/hotel/**
            filters:
              - StripPrefix=1

          - id: RATINGSERVICE
            uri: lb://RATINGSERVICE
            predicates:
              - Path=/rating/**
            filters:
              - StripPrefix=1
