#Eureka client properties to register service as a client on eureka server

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8090/eureka
spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
      - id: USERSERVICE
        uri: lb://USERSERVICE
        predicates:
          - Path=/users/**
          
      - id: HOTELSERVICE
        uri: lb://HOTELSERVICE
        predicates:
          - Path=/hotel/**
  
      - id: RATINGSERVICE
        uri: lb://RATINGSERVICE
        predicates:
          - Path=/rating/**
            
